#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

STALE_ENV_VAR_1=$(env | sort | awk -F "=" '{print $1}' | grep "^ODC[0-9]$")
STALE_ENV_VAR_2=$(env | sort | awk -F "=" '{print $1}' | grep "^OPC[0-9]$")
STALE_ENV_VAR_3=$(env | sort | awk -F "=" '{print $1}' | grep "^ODCC[0-9]$")
STALE_ENV_VAR_4=$(env | sort | awk -F "=" '{print $1}' | grep "^OPCC[0-9]$")

# shellcheck disable=SC2206
STALE_PUBLIC_OC_IPS=($STALE_ENV_VAR_1)
STALE_PRIVATE_OC_IPS=($STALE_ENV_VAR_2)
STALE_PUBLIC_OCC_IPS=($STALE_ENV_VAR_3)
STALE_PRIVATE_OCC_IPS=($STALE_ENV_VAR_4)

for ((i=0; i < ${#STALE_PUBLIC_OC_IPS[@]}; i++))
{
    pub_oc_name=${STALE_PUBLIC_OC_IPS[$i]}
    unset "$pub_oc_name"
}

for ((i=0; i < ${#STALE_PRIVATE_OC_IPS[@]}; i++))
{
    pri_oc_name=${STALE_PRIVATE_OC_IPS[$i]}
    unset "$pri_oc_name"
}

for ((i=0; i < ${#STALE_PUBLIC_OCC_IPS[@]}; i++))
{
    pub_occ_name=${STALE_PUBLIC_OCC_IPS[$i]}
    unset "$pub_occ_name"
}

for ((i=0; i < ${#STALE_PRIVATE_OCC_IPS[@]}; i++))
{
    pri_occ_name=${STALE_PRIVATE_OCC_IPS[$i]}
    unset "$pri_occ_name"
}

# shellcheck disable=SC1091
source $DIR/bash_profile

ENV_VAR_1=$(env | sort | awk -F "=" '{print $1}' | grep "^ODC[0-9]$")
ENV_VAR_2=$(env | sort | awk -F "=" '{print $1}' | grep "^OPC[0-9]$")
ENV_VAR_3=$(env | sort | awk -F "=" '{print $1}' | grep "^ODCC[0-9]$")
ENV_VAR_4=$(env | sort | awk -F "=" '{print $1}' | grep "^OPCC[0-9]$")

# shellcheck disable=SC2206
PUBLIC_OC_IPS=($ENV_VAR_1)
PRIVATE_OC_IPS=($ENV_VAR_2)
PUBLIC_OCC_IPS=($ENV_VAR_3)
PRIVATE_OCC_IPS=($ENV_VAR_4)
